title: Sandy's Website
email: sandy.zhengg23@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My Personal Website
baseurl: "https://sandyzhengg23.github.io/sandyzheng.github.io/" # the subpath of your site, e.g. /blog
url: "https://sandyzhengg23.github.io" # the base hostname & protocol for your site

theme: jekyll-theme-primer

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
